use strict;
use warnings;
use Module::Build;

my $builder = Module::Build->new(
    module_name         => 'App::ZofCMS::Plugin::TOC',
    license             => 'perl',
    dist_author         => 'Zoffix Znet <zoffix@cpan.org>',
    dist_version_from   => 'lib/App/ZofCMS/Plugin/TOC.pm',
    build_requires => {
        'Test::More' => 0,
    },
    requires => {
        'HTML::Template' => 2.9,
    },
    add_to_cleanup      => [ 'App-ZofCMS-Plugin-TOC-*' ],
    create_makefile_pl => 'traditional',
);

$builder->create_build_script();
